### ISSUE TITLE
Detect IOMMU

### ISSUE THREAD

**Issue by marquiz** [kubernetes-incubator/node-feature-discovery#136]
Detect if IOMMU is present (supported and enabled, by HW and the kernel).

**Comment by balajismaniam** [comment]
@marquiz what is the use-case for this?

**Comment by marquiz** [comment]
AFAIU, detecting correctly configured nodes for certain workloads. But, this is a fair question, I don't know have any concrete use case. @lmdaly: would you be able to elaborate on this?

**Comment by lmdaly** [comment]
That's correct Markus, the workload to be deployed should only deployed where IOMMU is enabled, if not we don't want the workload to land on that node.

**Comment by marquiz** [comment]
Also, DPDK workloads were mentioned in #119

**Comment by marquiz** [comment]
Implemented in #137. Closing this issue
