### ISSUE TITLE
Consider updating the label namespace

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes-incubator/node-feature-discovery#27]
Right now NFD publishes labels that begin with `node.alpha.intel.com`.
Does it make sense to change this to `node.alpha.kubernetes-incubator.io`?

cc @davidopp @timothysc @balajismaniam

**Comment by davidopp** [comment]
@bgrant0607

**Comment by timothysc** [comment]
I don't have strong opinions here, just know that someone is going to hard match on that label.

**Comment by ConnorDoyle** [comment]
@timothysc same here. We want to tag our first release soon but also want to avoid label churn (even though we will be in the `0.x.y` series.)

**Comment by fabiand** [comment]
I'd say that we can start with vendor labels - which got the "vendor freedom".
That allows us to have a quick start, and get vendors/sservices providing their labels for discovered functionality.

But on the mid-term run we maybe want to provide labels which have a defined name and values.
These labels should get the `io.kubernetes` prefix (I'm considering a reverse fqdn notation).

**Comment by ConnorDoyle** [comment]
@fabiand IMO reverse-fqdn is not advisable since it goes against precedent for alpha/beta prefixing already present in core Kubernetes.

As for vendor labels, so far there's a common prefix so that we can always track down labels that were added by this discovery pod. Each source (implementations of the `Source` interface in this project, there are a few already) has a name that goes into the label. Effectively the vendor namespace could be just `<common-prefix>/<vendor>`.

**Comment by ConnorDoyle** [comment]
Since there aren't too many objections here I'd like to get #27 merged (it's better IMO than the status quo: Intel's name on every label, that makes no sense.) We can continue to iterate if necessary.

**Comment by fabiand** [comment]
Yes, I don't have strong objections - my comment was merely a small comment.
