### ISSUE TITLE
Consider refactoring node-feature-discovery to run as a daemonset

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes-incubator/node-feature-discovery#34]
Instead of requiring the operator to configure a one-shot / periodic job, a node-feature-discovery daemon pod could be responsible for continuously fleecing node capabilities. This way eventually NFD could be included in cluster addons.

cc @jeremyeder @balajismaniam

**Comment by balajismaniam** [comment]
Currently, the discovery pod exits immediately after advertising the feature labels. As such it is setup as a one-shot job for simplicity and make sure it doesn't end up in a `CrashLoopBackOff` state. We might need to change how the discovery job runs (i.e., make it a daemon or long-running process) before switching to using DaemonSet.

**Comment by ConnorDoyle** [comment]
What do you think about a flag that tells NFD to daemonize itself instead of exiting after initial discovery?

**Comment by jeremyeder** [comment]
At the very least, we would want this as an option to NFD.

I agree we will see requests for a pluggable node agent to handle things like "extended-node-fitness": a deeper inspection of the node's running config and comparing it against a profile.

My desire is to use `tuned-adm verify` for this:
https://git.fedorahosted.org/cgit/tuned.git/tree/man/tuned-adm.8#n55

tuned is shipped in OpenSUSE (and Gentoo I believe).

**Comment by balajismaniam** [comment]
@ConnorDoyle Yes, that will work.

**Comment by thed00de** [comment]
I like the run to completion model.
And there are also requirements to have NFD detect changes to node features, capabilities etc. as they occur.

Is there any method currently with k8s, to have it execute the NFD pod on a node in response to a specific event on/for that node?

If not, would it be reasonable to consider a solution along those lines, either within k8s itself or externally with the appropriate k8s support?

**Comment by marquiz** [comment]
AFAIU making NFD a DaemonSet would be the only way to make sure that it is run on every node, and, that it would be automatically run on new nodes being added

**Comment by marquiz** [comment]
I'd propose closing this issue now that #105 has been merged.
