### ISSUE TITLE
Graceful failure if discovery from a source fails

### ISSUE THREAD

**Issue by IRCody** [kubernetes-incubator/node-feature-discovery#37]
Currently because of [this line](https://github.com/kubernetes-incubator/node-feature-discovery/blob/master/main.go#L128) whenever a source returns an error on it's Discover() call it causes nfd to fail.

I was wondering if it would it make sense to log the failure and proceed to discover features/add labels that nfd is able to instead of hard failing on any source failure?

**Comment by ConnorDoyle** [comment]
Great idea, we should also try to recover from panics that may occur when delegating to sources.

**Comment by balajismaniam** [comment]
+1.
