### ISSUE TITLE
Release version v0.1.0

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes-incubator/node-feature-discovery#40]
Use the [0.1.0 release milestone](https://github.com/kubernetes-incubator/node-feature-discovery/milestone/1) to track burndown.

- [x] All [OWNERS](OWNERS) must LGTM the release proposal.
- [x] Update the [job template](node-feature-discovery-job.json.template) to use the new tagged container image (PR #53)
- [x] An OWNER runs `git tag -s $VERSION` and insert the changelog into the tag description.
- [x] [Build and push](https://github.com/kubernetes-incubator/node-feature-discovery#building-from-source) a container image with the same tag to [quay.io](https://quay.io/kubernetes_incubator).
- [x] Update the `:latest` virtual tag in quay.io to track the last stable (this) release.
- [x] An OWNER pushes the tag with `git push $VERSION`.
- [x] Write the change log into the [Github release info](https://github.com/kubernetes-incubator/node-feature-discovery/releases).
- [x] Add a link to the tagged release in this issue.
- [x] An announcement email is sent to `kubernetes-dev@googlegroups.com` with the
   subject `[ANNOUNCE] node-feature-discovery $VERSION is released`
- [x] Close this issue.

**Comment by ConnorDoyle** [comment]
Proposed release notes:

- Use kubernetes-incubator.io in label namespace instead of intel.com.
- Graceful failure if discovery from a source fails.
- Use client-go instead of the unversioned client.
- Separate discovered features from logs in output (stdout/stderr).
- Delete non-discovered feature labels.
- Version string no longer part of published label key.
- Configure bots for repo management automation.
- Investigate and fix a number of issues from the quay.io vulnerability report.

**Comment by ConnorDoyle** [comment]
LGTM

**Comment by balajismaniam** [comment]
LGTM

**Comment by ConnorDoyle** [comment]
The tagged release is: https://github.com/kubernetes-incubator/node-feature-discovery/releases/tag/v0.1.0

**Comment by ConnorDoyle** [comment]
Announcement on kubernetes-dev: https://groups.google.com/forum/#!topic/kubernetes-dev/eOT43IU275w

**Comment by ConnorDoyle** [comment]
Checklist complete, closing.
