### ISSUE TITLE
Get the node object using spec.NodeName downward env var. 

### ISSUE THREAD

**Issue by balajismaniam** [kubernetes-incubator/node-feature-discovery#41]
We get the node object indirectly from the pod name using downward env var (see https://github.com/kubernetes-incubator/node-feature-discovery/blob/master/main.go#L212 and https://github.com/kubernetes-incubator/node-feature-discovery/blob/master/node-feature-discovery-job.json.template#L27). But `spec.NodeName` was added to the downward env vars. We should consider using it directly to get the node object.

**Comment by okartau** [comment]
just cosmetics: 
- line numbers in the original issue text need updating as source has changed.
- the correct variable name appears to be spec.nodeName

I made an attempt to implement the idea of this issue in #93 , is this what you had in mind?
Note that as there are no other users of POD-related variables, I deleted some code, I hope that's ok.
I verified this change works OK in my cluster.
