### ISSUE TITLE
org-wide CNCF CLA bot on kubernetes-incubator 

### ISSUE THREAD

**Issue by foxish** [kubernetes-incubator/node-feature-discovery#47]
Drawing attention to:https://groups.google.com/forum/#!topic/kubernetes-dev/Q9eNHdkIdQ0
As of tomorrow, the application of cncf labels and posting of the message in case someone has not signed it should be handled by our org-wide bot, and I would suggest that you disable the "cla" munger on the fork of mungegithub that you are currently running tomorrow evening, after we deploy. Otherwise, you're likely to see two sets of bots doing the same thing and possible interaction between them.

cc @balajismaniam @ConnorDoyle

**Comment by balajismaniam** [comment]
@foxish Thanks for letting us know. I will disable the CLA munger.

**Comment by balajismaniam** [comment]
Done. Closing this issue.

**Comment by ConnorDoyle** [comment]
Thanks @foxish and @balajismaniam
