### ISSUE TITLE
Built container wrongly describes version as "-dirty".

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes-incubator/node-feature-discovery#54]
The `.dockerignore` file in the repo excludes the `demo/` directory from the Docker context during build, which causes git to think there are uncommitted changes in the workspace.

**Comment by balajismaniam** [comment]
The reason we ignore `demo` directory was the input file size of the benchmarks used in the demo. This was fixed by https://github.com/kubernetes-incubator/node-feature-discovery/pull/19. Just removing `demo` directory from `.dockerignore` should be enough to fix this.
