### ISSUE TITLE
Spike: GPU feature discovery for NVIDIA cards

### ISSUE THREAD

**Issue by cmluciano** [kubernetes-incubator/node-feature-discovery#65]
I'd like to leverage NVML to detect specific features about NVIDIA cards on a given node.

Potential features:
- GPU family
- Architecture
- Maybe video memory?

**Comment by cmluciano** [comment]
cc @liyubobj @seelam

**Comment by ConnorDoyle** [comment]
Hey @cmluciano, glad to accept more feature sources! Please ping if you have any questions.

**Comment by liyubobj** [comment]
@cmluciano Yes, we also need video memory and GPU topology

**Comment by tianshapjq** [comment]
I've searched for a long time but seems no any nvml-lib in go released yet. Did you find any useful libs? thx :) @cmluciano

**Comment by Hui-Zhi** [comment]
@cmluciano ```Compute Capability``` and ```Driver version``` I think is very important to us.
- ```Compute capability``` could let customer know whether it could be used by some applications, like TensorFlow.
- ```Driver version``` could help the scheduler know whether a container can run on a node.

**Comment by cmluciano** [comment]
I will definitely look into those @Hui-Zhi . 

@tianshapjq You can try out [nvidia-docker](https://github.com/NVIDIA/nvidia-docker/tree/master/src/nvml).

**Comment by idealhack** [comment]
Agreed on Driver version, container mounting volumes need this. Currently I use:

```
{
    Name: "nvidia-driver",
    VolumeSource: apiv1.VolumeSource{
        HostPath: &apiv1.HostPathVolumeSource{
            Path: "/var/lib/nvidia-docker/volumes/nvidia_driver/384.47",
        },
    },
}
```

I was thinking if Kubernetes needs add `nvidia-docker` as a dependency to use NVML etc.

**Comment by cmluciano** [comment]
Yes I think the community is rallying behind hardware device plugins. I'm closing this in favor of https://github.com/kubernetes/community/pull/695. That proposal tracks the future of GPUs in k8s.
