### ISSUE TITLE
Hook up repo management automation

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes-incubator/node-feature-discovery#7]
- [x] CLA bot
- [x] Merge bot
- [x] CI
- [x] Mungers

**Comment by foxish** [comment]
@ConnorDoyle Addressing the first one: Is the intention to setup the Google CLA bot here?

**Comment by ConnorDoyle** [comment]
@foxish sorry for the delay. Yes, that's what we'd like to do. Eventually (soon?) it will all transition to CNCF CLA validation of some kind.

**Comment by foxish** [comment]
We're currently running a test on kubernetes/contrib with the CNCF CLA bot. We should be ready to roll it out to the entire kubernetes org by the week of 10/3. We could also shoot for the same timeline over here on incubator.

**Comment by balajismaniam** [comment]
@foxish That will be great.

**Comment by ConnorDoyle** [comment]
Re-opening (only the CI part was completed).

**Comment by foxish** [comment]
@ConnorDoyle The mungers/merge-bot part is independent from the CLA issue and can be setup for this repo. You could try the instructions at https://github.com/kubernetes/contrib/tree/master/mungegithub if you have access to a kubernetes cluster. We just deployed the CNCF CLA bot to https://github.com/kubernetes/contrib/ and are running tests.

**Comment by balajismaniam** [comment]
@ConnorDoyle do we really need the mungers and the merge-bot now? Can we start with CI and the CLA bot and work later on to setup the mungers and merge-bot?

**Comment by foxish** [comment]
Unfortunately, you'll need the mungegithub bot for the CLA system to work correctly. The bot applies the labels and notifies people, prompting them to sign, and the CLA webhook sets the status on each PR.

**Comment by balajismaniam** [comment]
@foxish mungegithub bot is running for the repo now. I've enabled the `blunderbuss,lgtm-after-commit,submit-queue,needs-rebase,lgtm-handler,cla` mungers for this repo. Can you please help us deploy the CNCF CLA bot for this repo. See #17 and #18. 

I have couple of questions for you: 
1. Is there a way to reduce the frequency of the CLA ping by the cla munger?
2. Does submit-queue play well with the github "approved reviews?" If yes, how do I enable it?

**Comment by foxish** [comment]
@balajismaniam The CLA ping is currently that frequent because the webhook itself is not turned on. Let me do that right away, org-wide on the incubator.

**Comment by balajismaniam** [comment]
Thank you.

**Comment by foxish** [comment]
@balajismaniam It is likely going to take a day, as we need the CNCF to accept their bot-user to accept membership into the kubernetes-incubator organization. For now, I'd suggest turning off the CLA munger, and re-enabling it after the webhook is setup completely.

/cc @emsearcy @caniszczyk

**Comment by balajismaniam** [comment]
Thanks for the help. 

Re: approvals, AFAICT submit-queue only looks at the mergeable field in the response to GET on the PR (see https://github.com/kubernetes/contrib/blob/master/mungegithub/mungers/submit-queue.go#L846 and https://github.com/kubernetes/contrib/blob/master/mungegithub/github/github.go#L1724) before merging. This doesn't prevent automatic merging as for example mergeable field is set to true for #17 even though it is not apporved. 

```sh
>curl https://api.github.com/repos/kubernetes-incubator/node-feature-discovery/pulls/17 | jq .mergeable
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21298  100 21298    0     0  22943      0 --:--:-- --:--:-- --:--:-- 22925
true
```

**Comment by foxish** [comment]
@balajismaniam Interesting, but the API call it makes is https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button in the end. I thought that would fail since you have protected branches turned on for this repository. I guess one could test it quite easily.

**Comment by balajismaniam** [comment]
@foxish Yes, the merge might not be successful. I will test it.

**Comment by balajismaniam** [comment]
Closing this issue since it is fixed. See the following:

CI: https://github.com/kubernetes-incubator/node-feature-discovery/pull/15. 
Merge Bot and Mungers: #17, #18 and #19. 
CLA bot: https://github.com/kubernetes-incubator/node-feature-discovery/pull/17#issuecomment-253255365.
