### ISSUE TITLE
Discover nodes with NUMA architecture

### ISSUE THREAD

**Issue by thedrow** [kubernetes-incubator/node-feature-discovery#84]
Software such as MongoDB or MySQL have known problems with NUMA architectures. See https://docs.mongodb.com/manual/administration/production-notes/#mongodb-and-numa-hardware and https://blog.jcole.us/2010/09/28/mysql-swap-insanity-and-the-numa-architecture/ for example.
It'd be useful to be able to select nodes without such architecture for such deployments.

**Comment by balajismaniam** [comment]
@thedrow Thanks for opening this issue. As always, PRs are welcome for this change :). 
FYI: there is active discussion in the Kubernetes community on NUMA awareness (see https://github.com/kubernetes/kubernetes/issues/49964). 
CC @ConnorDoyle

**Comment by okartau** [comment]
As there is no (AFAIK) simple readable flag "NUMA enabled", I think we could count online nodes under /sys/devices/system/node/ and create a label nfd-memory-multinode=true (or: nfd-memory-numamultinode any better?) if there is more than one node online.
/sys/devices/system/node/ seems to be source of information for 'numactl'. By reading /sys/devices directly, we can avoid dependency on numactl utility.
Would such a label serve the need here?
"memory" would become a new source.

**Comment by thedrow** [comment]
Yes it would.
