### ISSUE TITLE
Discover nodes with SSD/Rotational hard drives

### ISSUE THREAD

**Issue by thedrow** [kubernetes-incubator/node-feature-discovery#85]
It is often important for I/O intensive workloads to utilize SSDs. Being able to select nodes with an SSD available will make operating kubernetes clusters much easier.
For other workloads a rotational hard drive may be good enough.

**Comment by okartau** [comment]
NFD should create a binary label when current node has any SSD storage device attached?
Something like nfd-has-SSD=true ?
Or, should we avoid use of the SSD acronym but rely on same terms with /sys/block/
with something like nfd-has-non-rotational-storage-device=true ?
Note that labeling a node with one generic label will hide the information about
which devicehas rotational=0 attribute, creating trouble in mixed set-ups, and it is not guaranteed
how pods will be allocated onto mounted volumes and devices.
Creating a label per device would make detection possible at more detailed level,
but OTOH would add complexity to labels use.

**Comment by thedrow** [comment]
`nfd-has-non-rotational-storage-device=true` sounds good to me.
We'll leave the mounting of the correct device to the user.
We could also provide more detailed labeling later on but right now a boolean flag seems sufficient to me.
