### ISSUE TITLE
can we add the value of cpu-architecture into the label format

### ISSUE THREAD

**Issue by lubinszARM** [kubernetes-incubator/node-feature-discovery#86]
Hi all,
I'm from ARM. Currently I want to enable NFD in Arm platform.
But it seems that there is no value of cpu-architecture in the label.
So can we re-design the label format.

Please see reference in Openstack. There is a similar project in openstack. It's called 'os_traits'.
The label format in openstack is like this：  'HW_CPU_X86_AVX512ER', 'HW_CPU_X86_AVX512CD',

Please see this link as more reference: https://docs.openstack.org/os-traits/latest/user/index.html

**Comment by lubinszARM** [comment]
What's about this format: nfd-<module-name>-<cpu architecture >-<feature-name>.
For example: nfd-cpuid-x86-adx, nfd-cpuid-arm64-aes ...
@ncdc @redbaron @mumoshu @dims @slack

**Comment by dims** [comment]
cc @jaypipes

**Comment by mumoshu** [comment]
@lubinszARM Hi, I'm not familiar with ARM at all but why do you need to include the arch name in it?
 Wouldn't it be just like `ndf-<source>-<arm specific feature name>` if there's any arm specific feature, or `ndf-<source>-<common feature name>` for common features?

**Comment by jaypipes** [comment]
@mumoshu @lubinszARM I don't necessarily think you need to separate the "source" part of the label. The reason we used HW_CPU_X86_ as the prefix in os-traits was because each of the CPU capabilities represented in that module were Intel CPU instruction set extensions. Looking back, I suppose we could have gone with just HW_CPU_FEATURE_ as the prefix as well...

**Comment by jaypipes** [comment]
@lubinszARM think of os-traits "HW_CPU_X86_AES" as being the following:

 "HW" : hardware
 "CPU" : CPU-specific capability
 "X86_AES": Intel x86 instruction set extension for AES

**Comment by balajismaniam** [comment]
`Architecture` is already available under `NodeStatus`. https://github.com/kubernetes/api/blob/master/core/v1/types.go#L3817.

**Comment by marquiz** [comment]
Arch is also available in `beta.kubernetes.io/arch` node label. I suggest closing this issue. ping @balajismaniam @lubinszARM

**Comment by lubinszARM** [comment]
Agree
